server:
   servlet:
      context-path: /oa/
      multipart:
         max-file-size: 500MB
         max-request-size: 500MB
   port: 8089
   max-http-header-size: 1024000
spring:
  datasource:
    app:
      name: app
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      # 指定时区，避免时区问题
      jdbc-url: jdbc:mysql://localhost:3306/oa_app?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: lqb594107
      hikari:
        minimum-idle: 10
        maximum-pool-size: 50
      druid: 
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        filters: stat
    sys:
      name: sys
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/oa_sys?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&nullCatalogMeansCurrent=true
      username: root
      password: lqb594107
      hikari:
        minimum-idle: 10
        maximum-pool-size: 50
      druid: 
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        filters: stat
  resources:
       static-locations: classpath:/dist/,classpath:/angular/,classpath:/
  tomcat:
      max-active: 20
      max-wait: 60000  
      enabled: true
  http: 
     encoding: 
        force: true
        charset: UTF-8
        enabled: true
  activiti: 
      database-schema-update: true #自动更新数据库结构
      history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯
      db-history-used: true
      process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
      check-process-definitions: true #自动检查、部署流程定义文件
      #jobExecutorActivate: false # 关闭定时任务
      asyncExecutorActivate: false # 关闭计时器
      # 保存流程图乱码 这个方式无法解决
      #activityFontName: 宋体
      #labelFontName: 宋体
      #annotationFontName: 宋体
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      capital-mode: true
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      table-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
app: 
   name: oa
   description: 一很好的OA系统
ue: 
   config-file: static/ueditor/jsp/config.json
   server-url:  /ueditor.do
   local: 
      url-prefix:  /file/
      physical-path: /upload/